import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Toaster } from "react-hot-toast";
import { QueryProvider } from "@/components/ClientSideHelperFn";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QueryProvider>
        <GoogleOAuthProvider clientId="813194576123-pnhq43vv2nbjvf4r2qd86nndirp7ggbd.apps.googleusercontent.com">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
            <Toaster />
            <ReactQueryDevtools />
          </body>
        </GoogleOAuthProvider>
      </QueryProvider>
    </html>
  );
}
